# Generated by Django 5.2 on 2025-05-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(blank=True, default='unknown.jpg', null=True, upload_to='media/'),
        ),
    ]
