# Generated by Django 5.2 on 2025-05-22 19:39

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_candidate_recruiter_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name=users.models.CustomUser.__str__),
        ),
    ]
