# Generated by Django 5.2 on 2025-05-22 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_candidate_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='username',
        ),
    ]
