# Generated by Django 5.2 on 2025-05-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_candidate_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
