# Generated by Django 5.2 on 2025-05-22 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=75, null=True, verbose_name='Job Title')),
                ('contact_email', models.EmailField(blank=True, max_length=191, null=True, verbose_name='Contact Email')),
                ('description', models.TextField(blank=True, help_text='Detailed job description', null=True, verbose_name='Job Description')),
                ('responsibility', models.TextField(blank=True, help_text='Detailed job responsibilities', null=True, verbose_name='Job Responsibility ')),
                ('qualifications', models.TextField(blank=True, help_text='Detailed job qualifications', null=True, verbose_name='Job Qualifications ')),
                ('MinSalary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Min Salary ')),
                ('MaxSalary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Max Salary Amount')),
                ('category', models.CharField(choices=[('IT Services & Consulting', 'IT Services & Consulting'), ('Marketing', 'Marketing'), ('Customer Service', 'Customer Service'), ('Human Resource', 'Human Resource'), ('Project Management', 'Project Management'), ('Business Development', 'Business Development '), ('Sales & Communication', 'Sales & Communication'), ('Teaching & Education', 'Teaching & Education'), ('Design & Creative', 'Design & Creative')], default='office', max_length=75, verbose_name='Category')),
                ('remote', models.CharField(choices=[('Remote', 'Remote'), ('Hybrid', ' Remote'), ('On Site', 'On Site')], default='office', max_length=20, verbose_name='Remote Work Option')),
                ('location', models.CharField(blank=True, max_length=191, null=True, verbose_name='Job Location')),
                ('img', models.ImageField(blank=True, default='fallback.png', null=True, upload_to='', verbose_name='Company logo')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Posting Date')),
                ('poster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('status', models.CharField(choices=[('active', 'active'), ('closed', 'closed')], default='active', max_length=20, verbose_name='Job Status')),
                ('skills', models.CharField(blank=True, help_text='Comma-separated list of required skills', max_length=255, null=True, verbose_name='Required Skills')),
            ],
            options={
                'db_table': 'jobtech_job',
            },
        ),
    ]
