# Generated by Django 5.2.4 on 2026-02-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, help_text='Detailed cover letter', null=True, verbose_name='Cover Letter')),
                ('resume', models.FileField(upload_to='resumes/')),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'new'), ('interviewing', 'interviewing'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='new', max_length=20)),
                ('pertinency', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='Pertinency Score')),
            ],
            options={
                'db_table': 'jobtech_application',
            },
        ),
        migrations.CreateModel(
            name='interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=191, null=True)),
                ('status', models.CharField(blank=True, choices=[('accepted', 'accepted'), ('scheduled', 'scheduled'), ('rejected', 'rejected')], default='scheduled', max_length=20, null=True)),
            ],
            options={
                'db_table': 'jobtech_interview',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=75, null=True, verbose_name='Job Title')),
                ('contact_email', models.EmailField(blank=True, max_length=191, null=True, verbose_name='Contact Email')),
                ('description', models.TextField(blank=True, help_text='Detailed job description', null=True, verbose_name='Job Description')),
                ('responsibility', models.TextField(blank=True, help_text='Detailed job responsibilities', null=True, verbose_name='Job Responsibility ')),
                ('qualifications', models.TextField(blank=True, help_text='Detailed job qualifications', null=True, verbose_name='Job Qualifications ')),
                ('MinSalary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Min Salary ')),
                ('MaxSalary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Max Salary Amount')),
                ('category', models.CharField(choices=[('IT Services & Consulting', 'IT Services & Consulting'), ('Marketing', 'Marketing'), ('Customer Service', 'Customer Service'), ('Human Resource', 'Human Resource'), ('Project Management', 'Project Management'), ('Business Development', 'Business Development '), ('Sales & Communication', 'Sales & Communication'), ('Teaching & Education', 'Teaching & Education'), ('Design & Creative', 'Design & Creative')], default='office', max_length=75, verbose_name='Category')),
                ('applications', models.BigIntegerField(default=0, verbose_name='Number of Applications')),
                ('remote', models.CharField(choices=[('Remote', 'Remote'), ('Hybrid', ' Remote'), ('On Site', 'On Site')], default='office', max_length=20, verbose_name='Remote Work Option')),
                ('location', models.CharField(blank=True, max_length=191, null=True, verbose_name='Job Location')),
                ('img', models.ImageField(blank=True, default='fallback.png', null=True, upload_to='', verbose_name='Company logo')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Posting Date')),
                ('status', models.CharField(choices=[('active', 'active'), ('closed', 'closed')], default='active', max_length=20, verbose_name='Job Status')),
                ('skills', models.CharField(blank=True, help_text='Comma-separated list of required skills', max_length=255, null=True, verbose_name='Required Skills')),
            ],
            options={
                'db_table': 'jobtech_job',
            },
        ),
    ]
