# Generated by Django 5.2.4 on 2026-02-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobtech', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='img',
            field=models.ImageField(blank=True, default='fallback.png', null=True, upload_to='company_logos/', verbose_name='Company logo'),
        ),
    ]
