# Generated by Django 5.2 on 2025-05-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobTech', '0002_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='appliactions',
            field=models.BigIntegerField(default=0, verbose_name='Number of Applications'),
        ),
    ]
