# Generated by Django 5.2 on 2025-05-23 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobTech', '0003_job_appliactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='appliactions',
            new_name='applications',
        ),
    ]
