# Generated by Django 5.2 on 2025-05-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobTech', '0004_rename_appliactions_job_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
