# Generated by Django 5.2 on 2025-05-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobTech', '0005_job_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company_name',
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('interviewing', 'interviewing'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='applied', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('closed', 'closed')], default='active', max_length=20, verbose_name='Job Status'),
        ),
    ]
