# Generated by Django 5.2 on 2025-05-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobTech', '0006_remove_job_company_name_application_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.CharField(blank=True, help_text='Comma-separated list of required skills', max_length=255, null=True, verbose_name='Required Skills'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('interviewing', 'interviewing'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='new', max_length=20),
        ),
    ]
