# Generated by Django 5.2 on 2025-05-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobTech', '0009_interview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(blank=True, choices=[('accepted', 'accepted'), ('scheduled', 'scheduled'), ('rejected', 'rejected')], default='scheduled', max_length=20, null=True),
        ),
    ]
